version: '2'
services:

  app:
    build:
      context: ./
      dockerfile: app.docker
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - PHP_IDE_CONFIG=serverName=payment-system.d
      - DB_PORT=3306
      - DB_HOST=database
      - host=localhost

  web:
    build:
      context: ./
      dockerfile: web.docker
    working_dir: /var/www
    volumes_from:
      - app
    links:
      - app
    ports:
      - 8092:80

  composer:
    restart: 'no'
    image: composer
    command: install
    volumes_from:
      - app
    working_dir: /var/www

  node:
    image: "node:9"
    working_dir: /var/www
    environment:
      - NODE_ENV=development
    volumes:
      - ./:/var/www
    expose:
      - "8092"
    command: bash -c "npm install --save bootstrap -D bootstrap-sass -D && chmod -R u+x /var/www/node_modules && npm run watch"

  database:
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=payment_system
      - MYSQL_USER=payment_system
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports:
        - "33063:3306"

volumes:
  db:
